### ISSUE TITLE
Display state names in team embed footers

### ISSUE THREAD

**Issue by aopell** [glen3b/CyPatScoreboardBot#20]
It's wonderful that the team embed displays the team's state flag, but in practice very few people know more than their own state's flag. The team embed should display the name of the team's state, maybe in the footer.

**Comment by glen3b** [comment]
Perhaps with a syntax along the lines of `Location: California` or `Location: Australia`

**Comment by glen3b** [comment]
How should we resolve abbreviations to full state names? Probably through the flag resolution service, but what implementation? Is there a builtin? Easy web API?

**Comment by aopell** [comment]
Is it worth using an API for this? There are only 52 locations, I feel like despite being ugly the best way to do this is either a dictionary or a switch statement.

**Comment by glen3b** [comment]
We might want to have the mapping in a flatfile which we load on program start as opposed to hardcoding into the source code, but you're right - it's probably not worth dealing with an API. We'll want to watch out for licensing snags (although for a list of US states, Canada, and Australia, I doubt that will be an issue), but this should be trivial otherwise.
