### ISSUE TITLE
Export data to a CSV file

### ISSUE THREAD

**Issue by lighthouse64** [glen3b/CyPatScoreboardBot#41]
This feature would allow you to get an excel file from the data used to create a histogram.  It should work by division and tier, as well as by state.

Syntax:
!export [state]
!export [division] [tier]

**Comment by glen3b** [comment]
So basically export the entire scoreboard as a CSV? I have an owner-only JSON export feature, primarily intended for archiving the CCS scoreboard, but that isn't very spreadsheet-friendly.

**Comment by glen3b** [comment]
The export command will, in all likelihood, only return the summary information, because that's one API call. The reason the JSON export is restricted to owner-only is because it's O(n) in network calls (for CCS scoreboards) for n as team count - one call per team required to get details. However, it would still be straightforward to implement filtration by division and tier, and even by location and category. It would also allow joining categories from the category store (for CCS in particular), making more advanced filtration easier. Further processing should be trivial using awk, datamash, Excel, LibreOffice, or similar.

**Comment by glen3b** [comment]
The filtering of the data can be trivially done in spreadsheet software or command-line data processing tools, more so than in the bot. Thus, I'm closing this as completed.
